# generated by `python -m assay emit-tests` from rubrics.json - do not edit
"""Deterministic process checks for tortoise__tortoise-orm-943.

Task 150c282e-330b-492e-bcaf-1017bbfff2e8. Derived from rubrics.json: 8 load-bearing sites, 3 requirements a
target test already observes and 5 it does not.

Hard gates assert. Requirement outcomes are recorded rather than
asserted: this module's job is to produce a score and a readable
checklist, and failing every imperfect run would destroy both.

    pytest <corpus>/dataset/150c282e-330b-492e-bcaf-1017bbfff2e8/tests/test_output.py -v

Every task's module carries this same filename, matching tests/run_tests.py,
so running several at once needs --import-mode=importlib.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# This module lives at <corpus>/dataset/<uuid>/tests/, so both the
# corpus and the repo root follow from its own location. Counting
# parents and appending a fixed corpus name broke on a second corpus.
HERE = Path(__file__).resolve()
DELIVERY = HERE.parents[3]
ROOT = next(p for p in HERE.parents if (p / "assay" / "__init__.py").is_file())
sys.path.insert(0, str(ROOT))

from assay.bundle import RunBundle, TaskBundle  # noqa: E402
from assay.deterministic import (REQUIREMENT_WEIGHT, Gate,  # noqa: E402
                                 Verdict, evaluate)
from assay.truth import Truth  # noqa: E402

TASK_UUID = '150c282e-330b-492e-bcaf-1017bbfff2e8'
TASK_DIR = HERE.parent.parent
INSTANCE_ID = 'tortoise__tortoise-orm-943'


def _runs():
    # The task carries its own runs. An empty list here is invisible:
    # pytest reports no failure and no skip, only fewer tests.
    root = TASK_DIR / "trajectories"
    return sorted(p for p in root.glob("*/run_*") if p.is_dir())


@pytest.fixture(scope="module", params=_runs(),
                ids=lambda p: f"{p.parent.name}-{p.name}")
def report(request):
    task = TaskBundle(TASK_DIR)
    return evaluate(task, RunBundle(request.param), Truth.load(task.truth_path))


def _check(report, cid):
    found = [c for c in report.results if c.id == cid]
    assert found, f"{cid} was not evaluated; rubrics.json and this module disagree"
    return found[0]


def _record(report, record_property, cid):
    c = _check(report, cid)
    record_property(cid, f"{c.verdict.value} w={c.weight}")
    return c


class TestFairPlay:
    """Hard gates. A failure here voids the run outright."""

    def test_no_upstream_content_was_fetched(self, report):
        bad = [c for c in report.results
               if c.id.startswith("C1-") and c.is_hard_failure]
        assert not bad, "; ".join(c.detail for c in bad)

    def test_no_oracle_path_was_read(self, report):
        bad = [c for c in report.results
               if c.id.startswith("C2") and c.is_hard_failure]
        assert not bad, "; ".join(c.detail for c in bad)

    def test_graded_tests_were_not_rewritten(self, report):
        bad = [c for c in report.results
               if c.id.startswith(("C3", "C4", "C5")) and c.is_hard_failure]
        assert not bad, "; ".join(c.detail for c in bad)

    def test_the_run_and_the_bundle_agree(self, report):
        bad = [c for c in report.results
               if c.id.startswith(("A", "B")) and c.is_hard_failure]
        assert not bad, "; ".join(c.detail for c in bad)


class TestReachedTheLoadBearingSites:
    """One node per site truth.md names. Recorded, not asserted."""

    def test_reached_expressions(self, report, record_property):
        'tortoise/expressions.py'
        c = _record(report, record_property, 'E1-touched:tortoise/expressions.py')
        assert c.gate is Gate.SOFT

    def test_reached_query_utils(self, report, record_property):
        'tortoise/query_utils.py'
        c = _record(report, record_property, 'E1-touched:tortoise/query_utils.py')
        assert c.gate is Gate.SOFT

    def test_reached_functions(self, report, record_property):
        'tortoise/functions.py'
        c = _record(report, record_property, 'E1-touched:tortoise/functions.py')
        assert c.gate is Gate.SOFT

    def test_reached_queryset(self, report, record_property):
        'tortoise/queryset.py'
        c = _record(report, record_property, 'E1-touched:tortoise/queryset.py')
        assert c.gate is Gate.SOFT

    def test_reached_indexes(self, report, record_property):
        'tortoise/indexes.py'
        c = _record(report, record_property, 'E1-touched:tortoise/indexes.py')
        assert c.gate is Gate.SOFT

    def test_reached_timezone(self, report, record_property):
        'tortoise/timezone.py'
        c = _record(report, record_property, 'E1-touched:tortoise/timezone.py')
        assert c.gate is Gate.SOFT

    def test_reached_setup(self, report, record_property):
        'setup.cfg'
        c = _record(report, record_property, 'E1-touched:setup.cfg')
        assert c.gate is Gate.SOFT

    def test_reached_models(self, report, record_property):
        'tortoise/models.py'
        c = _record(report, record_property, 'E1-touched:tortoise/models.py')
        assert c.gate is Gate.SOFT


class TestRequirementsTheOutcomeChannelCannotSee:
    """Scored here, because no f2p/n2p test observes them.

    These are the whole reason the deterministic channel exists: a run can
    satisfy every target test and still miss all of them.
    """

    def test_s1_changed(self, report, record_property):
        'The reference change to tortoise/expressions.py is present. Any edit that achieves the same observable behaviour satisfies this.'
        c = _record(report, record_property, 'E2-req:S1-changed')
        assert c.weight > 0, "an unobserved requirement must be scored"

    def test_s2_removed(self, report, record_property):
        'The reference change to tortoise/query_utils.py is a removal, so the check asserts the removed code is not reinstated.'
        c = _record(report, record_property, 'E2-req:S2-removed')
        assert c.weight > 0, "an unobserved requirement must be scored"

    def test_s4_changed(self, report, record_property):
        'The reference change to tortoise/queryset.py is present. Any edit that achieves the same observable behaviour satisfies this.'
        c = _record(report, record_property, 'E2-req:S4-changed')
        assert c.weight > 0, "an unobserved requirement must be scored"

    def test_s5_changed(self, report, record_property):
        'The reference change to tortoise/indexes.py is present. Any edit that achieves the same observable behaviour satisfies this.'
        c = _record(report, record_property, 'E2-req:S5-changed')
        assert c.weight > 0, "an unobserved requirement must be scored"

    def test_s6_changed(self, report, record_property):
        'The reference change to tortoise/timezone.py is present. Any edit that achieves the same observable behaviour satisfies this.'
        c = _record(report, record_property, 'E2-req:S6-changed')
        assert c.weight > 0, "an unobserved requirement must be scored"


class TestRequirementsAlreadyPricedByTheOutcomeChannel:
    """Recorded only. `continuous_score_v2` already scores these through the
    f2p tests, so weighting them here would pay for one fact twice.
    """

    def test_s3_removed_is_recorded_not_scored(self, report, record_property):
        'The reference change to tortoise/functions.py is a removal, so the check asserts the removed code is not reinstated.'
        c = _record(report, record_property, 'E2-req:S3-removed')
        assert 0 < c.weight < REQUIREMENT_WEIGHT, (
            "already priced by the outcome channel, so discounted here; "
            "zero would lose the gradient entirely")

    def test_s7_changed_is_recorded_not_scored(self, report, record_property):
        'The reference change to setup.cfg is present. Any edit that achieves the same observable behaviour satisfies this.'
        c = _record(report, record_property, 'E2-req:S7-changed')
        assert 0 < c.weight < REQUIREMENT_WEIGHT, (
            "already priced by the outcome channel, so discounted here; "
            "zero would lose the gradient entirely")

    def test_s8_changed_is_recorded_not_scored(self, report, record_property):
        'The reference change to tortoise/models.py is present. Any edit that achieves the same observable behaviour satisfies this.'
        c = _record(report, record_property, 'E2-req:S8-changed')
        assert 0 < c.weight < REQUIREMENT_WEIGHT, (
            "already priced by the outcome channel, so discounted here; "
            "zero would lose the gradient entirely")


class TestTheScoreIsUsable:
    def test_score_is_well_formed(self, report):
        assert 0.0 <= report.soft_score <= 1.0

    def test_something_was_actually_scored(self, report):
        scored = [c for c in report.results
                  if c.gate is Gate.SOFT and c.weight > 0
                  and c.verdict is not Verdict.ABSTAIN]
        if any(c.id.startswith("A5") for c in report.hard_failures):
            pytest.skip("run has no trajectory")
        assert scored, "every scored check abstained, so the score is empty"

